import {StyleSheet} from 'react-native';
import {
  color,
  wp,
  hp,
  normalize,
  fonts,
  isIOS,
} from '../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.light_background,
  },

  mapStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flex: 1,
  },
  mapContainer: {
    // flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  upperBoxSafeArea: {
    position: 'absolute',
    zIndex: 100,
    width: wp(100),
    backgroundColor: color.white + '95',
  },
  upperBoxHeadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  currentMarker: {
    borderColor: color.white,
    borderWidth: wp(0.7),
    width: wp(5),
    height: wp(5),
    backgroundColor: color.sky,
    borderRadius: 100,
  },
  distanceContainer: {
    height: hp(30),
    width: wp(100),
    position: 'absolute',
    zIndex: 1000,
  },
  distanceText: {
    fontFamily: fonts.Lato_Regular,
    color: color.black_33,
    fontSize: normalize(60),
    alignSelf: 'center',
    marginTop: hp(10),
  },
  startButton: {
    position: 'absolute',
    bottom: hp(isIOS ? 12 : 10),
    zIndex: 1000,
  },
  afterRideButtonContainer: {
    alignSelf: 'center',
    flexDirection: 'row',
    width: wp(65),
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    bottom: hp(isIOS ? 12 : 10),
    zIndex: 1000,
  },
  absoluteButtonsView: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  gradientView: {
    flex: 1,
    alignSelf: 'center',
    width: wp(100),
    overflow: 'hidden',
    zIndex: 1000,
  },
  holeView: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    // backgroundColor: 'rgba(34,146,231,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  distanceLabel: {
    fontFamily: fonts.Lato_Regular,
    color: color.darkgray,
    fontSize: normalize(14),
    alignSelf: 'center',
  },
  sheetUpperView: {
    top: hp(2),
    width: wp(82),
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    textAlign: 'center',
  },
  sheetLowerView: {
    alignSelf: 'flex-start',
    left: wp(9),
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    textAlign: 'center',
    width: wp(46),
    top: hp(5),
  },
  blackTitleText: {
    width: wp(31),
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(16),
    color: color.black_33,
  },
  greyValueText: {
    top: hp(0.5),
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    color: color.gray,
  },
  pauseButton: {
    height: hp(4),
    width: wp(21.5),
    paddingVertical: hp(0),
    shadowRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
    zIndex: 100,
  },
  statusButton: {
    height: hp(4.7),
    width: wp(30),
    shadowRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
    paddingVertical: 0,
  },
  topBottomBorderContainer: {
    justifyContent: 'space-between',
    borderTopWidth: wp(0.1),
    borderBottomWidth: wp(0.1),
    borderColor: color.light_gray_backgraound,
    width: wp(100),
    alignItems: 'center',
  },
  rideBoxDetailsContainer: {
    marginTop: hp(2),
    paddingVertical: hp(3),
    paddingHorizontal: wp(10),
    flexDirection: 'row',
  },
  rideBoxBlackText: {
    width: '100%',
  },
  musicContainer: {
    paddingVertical: hp(2),
    paddingLeft: wp(10),
    paddingRight: wp(5),
    marginTop: hp(8),
    flexDirection: 'row',
  },
  musicControlsContainer: {
    flexDirection: 'row',
    width: wp(23),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  musicImage: {
    height: wp(15),
    width: wp(15),
    borderRadius: wp(1),
  },
  musicServiceTitle: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(11),
    color: color.darkgray,
  },
  musicName: {
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(16),
    color: color.black,
  },
  musicDetails: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(16),
    color: color.darkgray,
  },
});

export default styles;
