import {StyleSheet} from 'react-native';
import {
  color,
  fonts,
  hp,
  isANDROID,
  isIOS,
  normalize,
  wp,
} from '../../../../Helper/themeHelper';

const styles = StyleSheet.create({
  // General
  container: {flex: 1},
  distanceContainer: {
    height: hp(30),
    width: wp(100),
    position: 'absolute',
    zIndex: 1000,
    alignItems: 'center',
  },
  distanceText: {
    marginTop: hp(5),
    fontFamily: fonts.Lato_Regular,
    color: color.black_33,
    fontSize: normalize(60),
  },
  btnStartView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnStart: {
    height: hp(3.5),
    width: wp(23),
    paddingVertical: hp(0),
    shadowRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
  },
  historyModalHead: {
    marginTop: hp(2),
    alignItems: 'center',
    left: wp(4),
    flexDirection: 'row',
    backgroundColor: 'rgba(242,242,247,0.1)',
  },
  modalHeadTitle: {
    left: wp(7),
    fontSize: normalize(15),
    fontFamily: fonts.Lato_Regular,
    color: color.light_black,
  },
  setRouteText: {
    fontSize: normalize(15),
    fontFamily: fonts.Lato_Regular,
    color: color.sky,
  },
  buttonsContainer: {
    width: wp(80),
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: hp(7),
    zIndex: 1000,
  },
  musicButton: {
    backgroundColor: color.light_black,
    height: wp(11),
    width: wp(11),
    borderRadius: 100,
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: hp(7),
    zIndex: 1000,
  },
  musicImage: {
    alignSelf: 'center',
    position: 'absolute',
    bottom: hp(17),
    zIndex: 1000,
  },
  destinationName: {
    marginHorizontal: wp(2),
    alignSelf: 'flex-end',
    color: color.gray,
  },
  navigationRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: wp(0.1),
    borderBottomWidth: wp(0.1),
    borderColor: color.gray,
    paddingTop: hp(1),
    paddingBottom: hp(2),
    paddingLeft: wp(10),
    paddingRight: wp(7),
  },
  blackText: {
    color: color.black_33,
    fontSize: normalize(13),
    fontFamily: fonts.Lato_Bold,
  },

  // SetLocationScreen
  customText: {
    height: isANDROID ? hp(6) : hp(5),
    marginTop: hp(1),
    fontFamily: fonts.Lato_Regular,
    width: wp(75),
    fontSize: normalize(15),
    backgroundColor: color.light_background,
    borderRadius: 5,
    paddingLeft: wp(isIOS ? 5 : 4),
  },
  placeContainer: {
    borderTopWidth: wp(0.1),
    padding: wp(4),

    flexDirection: 'row',
    alignItems: 'center',
    borderColor: color.gray,
  },
  placeNameText: {
    fontSize: normalize(12),
    color: color.black,
    fontFamily: fonts.Lato_Regular,
    fontWeight: '600',
    width: wp(85),
  },
  placeAddressText: {
    top: hp(0.5),
    fontSize: normalize(12),
    color: color.darkgray,
    width: wp(85),
    fontFamily: fonts.Lato_Regular,
  },
  favRouteContainer: {
    borderTopWidth: wp(0.1),
    padding: wp(4),
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: color.gray,
    backgroundColor: color.white,
    borderBottomWidth: wp(0.1),
  },
  dashedLine: {
    left: wp(1.2),
    height: hp(3),
    borderRadius: 1,
    borderColor: color.gray,
    borderWidth: 1,
    width: 0,
    borderStyle: 'dashed',
  },
  favRouteTitleText: {
    fontSize: normalize(14),
    color: color.black,
    fontWeight: 'bold',
    fontFamily: fonts.Lato_Regular,
  },
  favRouteNameText: {
    color: color.black,
    marginHorizontal: wp(1),
    paddingVertical: hp(1),
    fontSize: normalize(13),
    fontFamily: fonts.Lato_Regular,
    fontWeight: 'bold',
  },
  favRoutesOriginText: {
    left: wp(2.5),
    fontSize: normalize(13),
    color: color.gray,
    width: wp(50),
  },
  favRoutesDestText: {
    left: wp(1),
    fontSize: normalize(13),
    color: color.gray,
  },
  noRecordsText: {
    alignSelf: 'center',
    color: color.gray,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
  },
  appBtn: {
    height: hp(4),
    width: wp(20),
    paddingVertical: hp(0.5),
  },
  navigationLocation: {
    borderTopWidth: 1,
    borderColor: color.gray,
    paddingVertical: hp(2),
    paddingHorizontal: wp(8),
  },
});

export default styles;
