require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
target 'olieApp' do


  config = use_native_modules!

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
 pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'



  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
 pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
 pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'RNSoundRecorder', :path => '../node_modules/react-native-sound-recorder'

  pod 'react-native-login-twitter', :path => '../node_modules/react-native-login-twitter'

  pod 'react-native-settings', :path => '../node_modules/react-native-settings'


  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  pod 'Firebase/Crashlytics'

  # add pods for any other desired Firebase products

  pod 'react-native-apple-music', :path => '../node_modules/@bouncyapp/react-native-apple-music'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'olieAppTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  use_native_modules!
end

target 'olieApp-tvOS' do
  # Pods for olieApp-tvOS

  target 'olieApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
