import {StyleSheet} from 'react-native';
import {color, fonts, hp, normalize, wp} from '../../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollBox: {
    height: wp(55),
    width: wp(55),
    marginLeft: wp(5),
    marginRight: wp(2),
    marginTop: hp(2),
    marginBottom: hp(5),
    borderRadius: wp(5),
    overflow: 'hidden',
  },
  newTabBotttom: {
    flex: 1,
    shadowOpacity: 0.6,
    shadowColor: color.gray,
    shadowRadius: 6,
    shadowOffset: {height: -2, width: 0},
    elevation: 2,
    backgroundColor: color.white,
    borderTopLeftRadius: wp(4),
    borderTopRightRadius: wp(4),
  },
  groupRidesAvatar: {
    height: hp(7),
    width: hp(7),
    borderRadius: hp(3.5),
    overflow: 'hidden',
  },
  blackText: {
    color: color.black_33,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
  },
  weatherText: {
    color: color.white,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
  },
  whiteText: {
    color: color.white,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
  },
  whiteBoldText: {
    color: color.white,
    fontSize: normalize(30),
    fontFamily: fonts.Lato_Bold,
  },
  groupRidesHeader: {
    backgroundColor: color.white,
    paddingBottom: hp(2),
    marginTop: hp(2),
    paddingHorizontal: wp(5),
    shadowOpacity: 0.6,
    shadowColor: color.gray,
    shadowRadius: 2,
    shadowOffset: {height: 3, width: 0},
    elevation: 2,
  },
  groupRidesRow: {
    flexDirection: 'row',
    // alignItems: 'center',
    paddingHorizontal: wp(8),
    paddingVertical: hp(1),
    marginVertical: hp(0.5),
    shadowOpacity: 0.6,
    backgroundColor: color.white,
    shadowColor: color.gray,
    shadowRadius: 2,
    shadowOffset: {height: 2, width: 0},
    elevation: 2,
  },
  groupRidesRowText: {
    color: color.darkgray,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
  },
  todayBtn: {
    backgroundColor: color.sky,
    justifyContent: 'center',
    paddingVertical: wp(1),
    paddingHorizontal: wp(2),
    borderRadius: wp(4),
    borderWidth: 2,
    borderColor: color.sky,
  },
  activityContainer: {
    flex: 1,
    paddingLeft: wp(8),
    paddingTop: hp(2),
    paddingBottom: hp(1.5),
    paddingRight: wp(3),
  },
  navigationContainer: {
    flex: 1,
    marginRight: wp(10),
    paddingHorizontal: wp(3),
    paddingTop: hp(2),
    paddingBottom: hp(1.5),
    backgroundColor: 'rgba(255,255,255, 0.3)',
  },
  weatherBottomContainer: {
    flex: 1,
    paddingHorizontal: wp(3),
    paddingTop: hp(2),
    paddingBottom: hp(1.5),
    backgroundColor: 'rgba(255,255,255, 0.6)',
    borderRadius: wp(3),
  },
  mapIcon: {
    height: hp(3),
    width: hp(3),
  },
  activityModalcontainer: {
    flex: 1,
    paddingVertical: hp(2),
    borderRadius: wp(5),
    overflow: 'hidden',
    backgroundColor: color.white + '20',
  },
  activityMileView: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: color.white,
    paddingTop: hp(2),
    paddingBottom: hp(3),
    alignItems: 'center',
  },
  activityDetailView: {
    borderBottomWidth: 1,
    borderColor: color.white,
    paddingVertical: hp(1.5),
  },
  ShopDetailView: {
    borderBottomWidth: 0.8,
    borderColor: color.white,
    paddingVertical: hp(1.8),
    paddingHorizontal: wp(6),
  },
  mileText: {
    fontSize: normalize(44),
    marginTop: hp(2),
    marginBottom: hp(1),
  },
  navigationFooterContainer: {
    flexDirection: 'row',
    paddingVertical: hp(2),
    alignItems: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: color.gray,
  },
  navigationRowContainer: {
    borderTopWidth: 1,
    borderColor: color.gray,
    paddingVertical: hp(2),
    paddingHorizontal: wp(8),
  },
  navigationBottomContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  startBtn: {
    height: hp(4),
    width: wp(20),
    paddingVertical: hp(0.5),
  },
  regularText: {
    fontFamily: fonts.Lato_Regular,
    color: color.gray,
    fontSize: normalize(16),
    alignSelf: 'center',
  },
  inputTextStyle: {
    marginHorizontal: wp(20),
    alignItems: 'center',
    color: color.black,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: 'red',
    borderColor: color.gray,
  },
  rankContainer: {
    position: 'absolute',
    top: 0,
    left: -wp(2),
    height: wp(6),
    width: wp(6),
    backgroundColor: color.lightpink,
    borderRadius: wp(3),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: wp(0.5),
    borderColor: color.pink,
    zIndex: 1000,
  },
  rankingText: {
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
    color: color.white,
  },
});

export default styles;
