import {StyleSheet} from 'react-native';
import {color, fonts, hp, normalize, wp} from '../../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.white,
  },
  headingText: {
    color: color.sky,
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Bold,
  },
  blackBoldText: {
    color: color.black_33,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Bold,
  },
  blackText: {
    color: color.black_33,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
  },
  grayText: {
    color: color.gray,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
  },
  profileImgMain: {
    height: wp(16),
    width: wp(16),
    borderRadius: wp(8),
    marginRight: wp(3),
  },
  profileImgSub: {
    height: wp(6),
    width: wp(6),
    borderRadius: wp(3),
    marginLeft: wp(-1.5),
    backgroundColor: color.sky,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: color.white,
    marginBottom: hp(1),
  },
  favouriteContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: wp(3),
    paddingVertical: hp(1),
  },
  groupContainer: {
    paddingVertical: hp(2),
    paddingHorizontal: wp(6),
    marginHorizontal: 0,
    marginVertical: hp(0.5),
    shadowOpacity: 0.6,
    backgroundColor: color.white,
    shadowColor: color.gray,
    shadowRadius: 2,
    shadowOffset: {height: 3, width: 0},
    elevation: 3,
  },
  favouriteHeading: {
    marginVertical: hp(1),
    marginLeft: wp(5),
  },
  favouriteFlatlist: {
    backgroundColor: color.white,
    shadowColor: color.gray,
    shadowOpacity: 0.6,
    shadowRadius: 2,
    shadowOffset: {height: 3, width: 0},
    elevation: 2,
  },
  selectedParticipantMainView: {
    paddingVertical: hp(1),
    paddingHorizontal: wp(6),
  },
  groupNameInputContainer: {
    flex: 1,
    borderBottomWidth: 0.5,
    borderColor: color.gray,
    borderTopWidth: 0.5,
    justifyContent: 'center',
    marginLeft: wp(5),
    marginTop: hp(0.5),
    height: hp(7),
  },
  groupDateInputContainer: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: color.gray,
    justifyContent: 'center',
    marginLeft: wp(5),
    height: hp(7),
  },
  selectedGroupImage: {
    width: '35%',
    height: '35%',
    // borderWidth: 0.5,
  },
  imageGroupStyle: {
    width: wp(18),
    height: wp(18),
    borderRadius: wp(9),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.light_background,
    overflow: 'hidden',
  },
  imageSpaceStyle: {
    width: wp(15),
    height: wp(15),
    borderRadius: wp(7.5),
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.white,
    // borderWidth: 0.5,
  },
  sideTextStyle: {
    flex: 1,
    color: color.green_background,
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Regular,
  },
  selectedContactButtonView: {
    height: hp(2),
    width: hp(2),
    backgroundColor: color.sky,
    borderRadius: hp(2),
    position: 'absolute',
    top: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedParticipantImage: {
    width: wp(8.5),
    height: wp(8.5),
    borderRadius: wp(4.25),
    // borderWidth: 0.5,
  },
  selectedContactMainView: {
    paddingVertical: hp(1),
    paddingHorizontal: wp(4),
  },
  selectedContactInnerView: {
    paddingHorizontal: wp(1.5),
    paddingVertical: hp(1),
    borderColor: color.gray,
    borderBottomWidth: 0.5,
  },
  locationContainer: {
    height: hp(7),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(7),
    borderBottomWidth: 1,
    borderColor: color.gray,
  },
  locationText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    marginLeft: wp(5),
    color: color.gray,
  },
  locationAddress: {
    marginTop: hp(0.5),
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    marginLeft: wp(5),
    color: color.gray,
    marginRight: wp(2),
  },
  headerContainer: {
    backgroundColor: color.white,
    borderBottomWidth: 0.5,
    borderColor: color.gray,
  },
  groupDetailContainer: {
    flexDirection: 'row',
    paddingHorizontal: wp(5),
    paddingVertical: hp(3.7),
  },
  groupPhoto: {
    resizeMode: 'contain',
    flex: 1,
    height: '40%',
    width: '40%',
  },
  graySpace: {
    backgroundColor: color.light_background,
    height: hp(4),
    justifyContent: 'center',
    paddingHorizontal: wp(4),
  },
  websiteContainer: {
    height: hp(6),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(10),
  },
  websiteInput: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    marginLeft: wp(6),
  },
  dateContainer: {
    height: hp(6),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(10),
  },
  dateText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    color: color.gray,
    marginLeft: wp(6),
  },
  locContainer: {
    height: hp(6),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(10),
  },
  locationInput: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    marginLeft: wp(6),
  },
  locationsContainer: {
    backgroundColor: color.light_background,
    borderColor: color.gray,
    borderTopWidth: 1,
  },
  minParticipantContainer: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    borderColor: color.gray,
    borderBottomWidth: 1,
  },
  minText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    color: color.gray,
  },
  maxText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    color: color.gray,
  },
  maxInput: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    flex: 1,
  },
  descText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    color: color.gray,
  },
  descSubText: {
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(10),
    color: color.gray,
    marginRight: wp(4.2),
  },
  descInput: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    flex: 1,
    marginTop: hp(1),
    marginRight: wp(3),
  },
  calendarContainer: {
    backgroundColor: '#ffffff',
    padding: 50,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarBtn: {
    color: color.white,
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(12),
  },
  ModalContainer: {
    backgroundColor: '#000000aa',
    flex: 1,
    justifyContent: 'center',
  },
  userNameText: {
    marginLeft: wp(7),
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
    color: color.light_black,
  },
  locations2Container: {
    height: hp(7),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(7),
    borderBottomWidth: 1,
    borderColor: color.gray,
  },
  locations2Text: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    marginLeft: wp(5),
    color: color.gray,
  },
  locations2Address: {
    marginTop: hp(0.5),
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    marginLeft: wp(5),
    color: color.gray,
    marginRight: wp(2),
  },
  headerStyle: {
    backgroundColor: color.white,
    borderBottomWidth: 0.5,
    borderColor: color.gray,
  },
  group2Image: {
    resizeMode: 'contain',
    flex: 1,
    height: '40%',
    width: '40%',
  },
  calendar2Container: {
    height: hp(6),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(10),
  },
  calendar2Text: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    color: color.gray,
    marginLeft: wp(6),
  },
  location2Container: {
    height: hp(6),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(10),
  },
  location2Input: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    marginLeft: wp(6),
  },
  calenderModalContainer: {
    backgroundColor: '#ffffff',
    padding: 50,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  participantContainer: {
    backgroundColor: color.light_background,
    height: hp(4),
    justifyContent: 'center',
    paddingHorizontal: wp(4),
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: color.gray,
  },
  adminContainer: {
    marginLeft: wp(7),
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
    color: color.light_black,
    flex: 1,
  },
  adminsubText: {
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
    color: color.gray,
  },
});

export default styles;
