import {StyleSheet} from 'react-native';
import {
  color,
  fonts,
  hp,
  isANDROID,
  normalize,
  wp,
} from '../../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.light_background,
  },
  challengeItemBg: {
    flex: 1,
    marginVertical: hp(2),
    marginHorizontal: wp(5),
    borderRadius: hp(10),
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
    elevation: 25,
  },
  linearGradientBg: {
    flex: 1,
    borderRadius: wp(3),
  },
  btnBg: {flex: 1, marginVertical: hp(2)},
  titleTextStyle: {
    fontFamily: fonts.Lato_Bold,
    color: color.white,
    flex: 1,
    fontSize: normalize(25),
    marginVertical: hp(0),
  },

  imageStyle: {
    height: hp(12),
    width: hp(12),
    borderRadius: hp(7.5),
    overflow: 'hidden',
    marginVertical: hp(2.5),
    alignSelf: 'center',
  },
  challengeTypeText: {
    fontFamily: fonts.Lato_Bold,
    color: color.white,
    flex: 1,
    fontSize: normalize(20),
    marginVertical: hp(0),
  },

  descriptionText: {
    fontFamily: fonts.Lato_Bold,
    color: color.white,
    flex: 1,
    fontSize: normalize(15),
    marginVertical: hp(1),
  },
  modelBg: {
    backgroundColor: color.gray,
    flex: 1,
    margin: wp(27),
    marginHorizontal: wp(5),
    borderRadius: hp(10),
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
    elevation: 25,
  },
  modalImageBg: {
    flex: 1,
    borderRadius: wp(5),
    alignSelf: 'center',
    width: wp(65),
    height: hp(13),
    marginVertical: hp(2.5),
  },
  textModal: {
    fontFamily: fonts.Lato_Bold,
    color: color.white,
    fontSize: normalize(20),
    marginVertical: hp(0),
    marginHorizontal: wp(10),
  },
  textTitle: {
    fontFamily: fonts.Lato_Bold,
    color: color.black,
    textAlign: 'center',
    fontSize: normalize(14),
  },
  regularText: {
    fontFamily: fonts.Lato_Regular,
    color: color.gray,
    textAlign: 'center',
    fontSize: normalize(14),
  },
  modalTextHeader: {
    fontFamily: fonts.Lato_Bold,
    color: color.white,
    flex: 0.2,
    fontSize: normalize(25),
    marginVertical: hp(1),
    marginHorizontal: wp(10),
  },

  modalDescription: {
    fontFamily: fonts.Lato_Bold,
    color: color.white,
    fontSize: normalize(15),
    marginVertical: hp(1),
    marginHorizontal: wp(10),
  },
  blurView: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  buttonLayout: {
    justifyContent: 'flex-end',
    paddingHorizontal: wp(3),
  },
  inputContainer: {
    marginHorizontal: wp(20),
    borderColor: color.gray,
    height: hp(4),
    paddingVertical: hp(0),
    borderRadius: 20,
    borderWidth: 1,
  },
  inputTextStyle: {
    marginHorizontal: wp(15),
    alignItems: 'center',
    color: color.black,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: color.gray,
  },
  addButton: {
    width: wp(50),
    alignSelf: 'center',
    paddingVertical: hp(0),
    marginHorizontal: wp(35),
    height: hp(5),
    padding: hp(0),
    borderRadius: hp(0.5),
    shadowOpacity: 0,
    elevation: 0,
    marginBottom: hp(3),
  },
  facebookBtn: {
    alignSelf: 'center',
    paddingVertical: hp(0),
    borderRadius: hp(4),
    height: isANDROID ? hp(6) : hp(5),
    width: wp(60),
    marginHorizontal: wp(15),
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  bottomView: {
    backgroundColor: color.white,
    marginHorizontal: wp(6),
    borderRadius: wp(3),
    paddingVertical: hp(3),
    shadowColor: color.gray,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
  topContainer: {
    backgroundColor: color.white,
    marginVertical: hp(2),
    marginHorizontal: wp(6),
    borderRadius: wp(3),
    shadowColor: color.gray,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
});

export default styles;
