import {StyleSheet} from 'react-native';
import {
  color,
  fonts,
  hp,
  isANDROID,
  normalize,
  wp,
} from '../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.light_background,
  },
  newContactText: {
    paddingHorizontal: hp(3),
    fontSize: normalize(14),
    color: color.sky,
    paddingVertical: hp(1),
  },
  labelContactText: {
    flex: 0.5,
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(10),
  },
  contactValuesText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    marginHorizontal: wp(0),
    color: color.sky,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactHeader: {
    color: color.black_33,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
  },
  contactIconContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp(6),
    paddingVertical: hp(1),
    flex: 1,
    marginLeft: wp(8),
  },
  separatorContainer: {
    justifyContent: 'space-between',
    backgroundColor: color.light_gray_backgraound,
    height: hp(4),
    marginTop: hp(1),
  },
  blackText: {
    color: color.black_33,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
  },
  whiteText: {
    color: color.white,
    fontSize: normalize(10),
    fontFamily: fonts.Lato_Regular,
  },

  grayText: {
    color: color.gray,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
  },
  profileImgMain: {
    height: wp(14),
    width: wp(14),
    borderRadius: wp(7),
    marginHorizontal: wp(3),
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(6),
    paddingVertical: hp(1),
    backgroundColor: color.light_background,
    borderBottomWidth: 0.4,
    borderColor: color.gray,
  },
  todayBtn: {
    backgroundColor: color.darkPink,
    justifyContent: 'center',
    paddingVertical: wp(0.5),
    paddingHorizontal: wp(1),
    borderRadius: wp(4),
    borderWidth: 2,
    borderColor: color.darkPink,
    marginLeft: wp(2),
  },
  mainMapContainer: {
    paddingHorizontal: wp(5),
    backgroundColor: color.white,
  },
  inputContainer: {
    backgroundColor: color.lightgray,
    borderRadius: wp(1),
  },
  inputStyle: {
    fontSize: normalize(16),
    marginHorizontal: wp(1),
    zIndex: 100,
  },
  mapHeadContainer: {
    marginBottom: hp(5),
    marginHorizontal: wp(2),
  },
  headCompContainer: {
    flexDirection: 'row',
    marginHorizontal: wp(2),
    marginVertical: hp(2),
  },
  headCancel: {
    flex: 1,
    marginTop: hp(1),
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Regular,
    color: color.sky,
  },
  headTitle: {
    flex: 1,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
  },
  headRefresh: {
    flex: 1,
    width: wp(5),
    height: hp(5),
    marginTop: hp(1),
    alignSelf: 'flex-end',
  },
  searchContainer: {
    marginHorizontal: wp(4),
  },
  liveLocation: {
    width: hp(3.5),
    height: hp(3.5),
  },
  locationView: {
    flex: 1,
    marginTop: hp(2),
    backgroundColor: color.light_background,
  },
  locationListView: {
    marginLeft: wp(8),
    height: hp(5),
    alignItems: 'center',
    flexDirection: 'row',
  },
  sendLiveText: {
    flex: 1,
    marginLeft: wp(3),
    alignSelf: 'center',
    fontFamily: fonts.Lato_Regular,
    color: color.sky,
    fontSize: normalize(14),
    justifyContent: 'center',
  },
  nearByTextView: {
    height: hp(5),
    backgroundColor: color.white,
    justifyContent: 'center',
  },
  nearByText: {
    flex: 1,
    color: color.black_33,
    marginTop: hp(2),
    marginVertical: hp(0),
    marginHorizontal: wp(18),
    alignItems: 'center',
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    justifyContent: 'center',
  },
  listLocationView: {
    borderBottomWidth: 1,
    borderColor: color.gray,
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: hp(1.5),
  },
  locationImage: {
    marginRight: wp(2),
    marginLeft: wp(5),
    width: wp(8),
    height: wp(8),
  },
  locationTitleView: {
    flex: 1,
    justifyContent: 'center',
  },
  locationTitle: {
    // marginVertical: 5,
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    color: color.black_33,
  },
  locationSubTitle: {
    fontFamily: fonts.Lato_Regular,
    color: color.gray,
    fontSize: normalize(12),
    justifyContent: 'center',
  },
  /*Styling of SharedContact View*/
  contactContainer: {
    paddingHorizontal: wp(5),
    // paddingVertical: hp(1),
    backgroundColor: color.lightest_gray,
  },

  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: hp(2),
    marginHorizontal: wp(3),
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  rowContactStyle: {
    paddingVertical: hp(1),
    flex: 2,
    marginLeft: wp(8),
  },
  imageRowStyle: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    // borderWidth: 0.5,
    overflow: 'hidden',
  },
  imageNameContainer: {
    height: wp(14),
    width: wp(14),
    borderRadius: wp(7),
    marginTop: hp(1),
  },
  logoInRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(20),
    marginRight: wp(2),
  },
  sideTextStyle: {
    flex: 1,
    color: color.sky,
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Regular,
  },
  headerTextStyle: {
    color: color.black,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
  },
  contactInputContainer: {
    marginBottom: hp(2),
    backgroundColor: color.lightgray,
    borderRadius: wp(0),
    borderWidth: 0,
  },
  contactInputStyle: {
    fontSize: normalize(16),
    marginHorizontal: wp(1),
    borderWidth: 0,
  },
  sectionHeader: {
    paddingTop: 2,
    paddingLeft: wp(5),
    paddingRight: 10,
    paddingBottom: 2,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Bold,
    color: color.black,
    backgroundColor: color.light_background,
  },
  item: {
    padding: wp(2),
    fontSize: normalize(16),
    paddingLeft: wp(8),
  },
  viewOfImageStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(20),
    marginRight: wp(2),
  },
  imageStyle: {
    height: wp(5),
    width: wp(5),
    marginTop: hp(10),
  },
  checkedCircle: {
    marginTop: 10,
    marginHorizontal: wp(2),
  },
  checkBoxView: {backgroundColor: color.green_background},
  itemSeparatorStyle: {
    height: hp(0.1),
    backgroundColor: color.gray,
  },
  scrollBox: {
    flex: 1,
    height: hp(20),
    width: hp(18),
    marginLeft: wp(6),
    // marginRight: wp(2),
    marginTop: hp(2),
    marginBottom: hp(5),
    borderRadius: wp(5),
    backgroundColor: color.white,
    shadowColor: color.gray,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
  leftImage: {
    height: hp(8),
    width: hp(8),
    overflow: 'hidden',
    left: 20,
    alignSelf: 'center',
    borderRadius: hp(4),
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
  },

  btnLabelStyle: {
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(15),
    fontWeight: '700',
  },
  btnView: {flex: 1, marginLeft: wp(4)},
  centerImage: {
    height: hp(13),
    width: hp(13),
    borderRadius: hp(6.5),
    borderWidth: wp(1),
    borderColor: 'white',
    overflow: 'hidden',
    zIndex: 3,
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
  },

  rightImage: {
    height: hp(8),
    width: hp(8),
    overflow: 'hidden',
    right: 20,
    alignSelf: 'center',
    borderRadius: hp(4),
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
  },

  headerText: {
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
    alignSelf: 'center',
    color: color.black_33,
    marginVertical: hp(2),
  },
  addOrFindButton: {
    width: wp(30),
    alignSelf: 'center',
    marginHorizontal: wp(1),
    borderRadius: hp(0.5),
    shadowRadius: 0,
    fontFamily: fonts.Lato_Bold,
    fontWeight: 'bold',
    fontSize: normalize(14),
    shadowColor: 0,
    elevation: 0,
  },
  findFriendBtnStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: hp(2),
    marginHorizontal: wp(3),
  },
  buttonStyle: {flex: 1, marginRight: wp(4)},
  textBold: {
    marginVertical: hp(1),
    marginHorizontal: wp(6),
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
    color: color.black_33,
  },
  suggestedFriendImage: {
    marginVertical: hp(1),
    height: hp(8),
    width: hp(8),
    borderRadius: hp(5),
    overflow: 'hidden',
    alignSelf: 'center',
  },
  addButton: {
    width: wp(20),
    height: hp(4),
    alignSelf: 'center',

    paddingVertical: hp(0),
    marginHorizontal: wp(2),
    marginVertical: hp(2),
    backgroundColor: color.sky,
    borderRadius: hp(0.5),
    shadowRadius: 0,
    shadowColor: 0,
    elevation: 0,
  },
  indexContainer: {
    flex: 1,
    marginVertical: hp(2),
    marginHorizontal: wp(6),
    borderRadius: hp(2),
    shadowColor: color.gray,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
    backgroundColor: color.white,
  },

  //styles for Message Contact (shared Contact List)
  contactMsgContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(50),
    height: hp(8),
  },
  contactTouchable: {
    borderRadius: wp(5),
    width: wp(50),
    height: wp(14),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: color.lightSky,
  },
  contactName: {
    flex: 1,
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(14),
    color: color.black_33,
  },
  contactListName: {
    fontFamily: fonts.Lato_Bold,
    flex: 1,
    fontSize: normalize(16),
    marginHorizontal: wp(11),
    justifyContent: 'center',
    alignItems: 'center',
  },
  pdfRedirectBtn: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    maxWidth: wp(70),
    paddingVertical: hp(0.5),
    paddingHorizontal: wp(5),
  },
  pdfName: {
    marginVertical: hp(0.5),
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(14),
    textAlign: 'left',
    marginHorizontal: wp(2),
  },

  rowStyle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swipeToCancel: {
    fontFamily: fonts.Lato_Bold,
    color: color.gray,
    fontSize: normalize(14),
    textAlign: 'center',
  },
  connectBtn: {
    color: color.white,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Bold,
  },
  connectBtnOuter: {
    backgroundColor: color.sky,
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.8),
    borderRadius: wp(2),
  },
  connectBtnContainer: {
    backgroundColor: 'rgba(242, 242, 247, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: color.gray,
    paddingTop: hp(2),
  },
  placeContainer: {
    borderTopWidth: wp(0.1),
    padding: wp(4),
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: color.gray,
  },
  placeNameText: {
    fontSize: normalize(12),
    color: color.black,
    fontFamily: fonts.Lato_Regular,
    fontWeight: '600',
    width: wp(85),
  },
  placeAddressText: {
    top: hp(0.5),
    fontSize: normalize(12),
    color: color.darkgray,
    width: wp(85),
    fontFamily: fonts.Lato_Regular,
  },
});

export default styles;
