import {StyleSheet} from 'react-native';
import {
  color,
  fonts,
  hp,
  normalize,
  wp,
  isANDROID,
} from '../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  btnRecentRide: {
    marginVertical: hp(1),
    justifyContent: 'center',
    marginHorizontal: wp(3),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1),
    alignItems: 'center',
    position: 'absolute',
    zIndex: 100,
    top: hp(1),
    borderWidth: hp(0.2),
    borderColor: color.sky,
    backgroundColor: color.white,
  },
  btnRecentRideText: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(12),
    color: color.sky,
  },
  gradientView: {
    flex: 1,
    alignSelf: 'center',
    width: wp(110),
    overflow: 'hidden',
    zIndex: 1000,
  },
  holeView: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    // backgroundColor: 'rgba(34,146,231,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrCodeUserText: {
    flex: 1,
    marginHorizontal: wp(7),
    top: hp(1),
    fontSize: normalize(13),
    fontFamily: fonts.Lato_Bold,
    color: color.gray,
  },
  qrCodeView: {
    flex: 4,
    marginVertical: hp(5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButton: {
    width: wp(20),
    height: hp(4),
    alignSelf: 'center',

    paddingVertical: hp(0),
    marginHorizontal: wp(2),
    marginVertical: hp(0),
    backgroundColor: color.sky,
    borderRadius: hp(0.5),
    shadowRadius: 0,
    shadowColor: 0,
    elevation: 0,
  },
  closeBtn: {
    alignSelf: 'flex-end',
    right: wp(2),
    top: hp(1),
  },
  buttonLayout: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: wp(3),
  },
  profileImage: {
    marginTop: hp(3),
    width: wp(30),
    height: wp(30),
    borderRadius: wp(15),
    borderWidth: 1,
    borderColor: color.gray,
    overflow: 'hidden',
  },
  userNameText: {
    fontFamily: fonts.Lato_Regular,
    color: color.gray,
    marginVertical: 5,
    fontSize: normalize(10),
  },
  infoContainer: {
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: hp(2),
  },
  mapContainer: {
    flex: 2,
    marginVertical: hp(2),
    borderWidth: 0,
    height: hp(30),
    width: wp(100),
  },
  progressBar: {
    marginVertical: hp(1),
    alignSelf: 'center',
    flexDirection: 'row',
    height: hp(0.7),
    width: wp(88),
    backgroundColor: color.gray,
    borderRadius: 5,
  },
  inputContainer: {
    marginBottom: hp(3),
  },
  proFeatureContainer: {
    flexDirection: 'row',
    marginHorizontal: wp(2),
    marginTop: hp(1),
    alignItems: 'center',
  },
  proFeatureText: {
    color: color.white,
    marginLeft: wp(1),
    fontSize: normalize(10),
    fontFamily: fonts.Lato_Regular,
    flex: 1,
  },
  basicFeatureContainer: {
    flexDirection: 'row',
    marginHorizontal: wp(1),
    marginTop: hp(1),
    alignItems: 'center',
  },
  basicFeatureText: {
    color: color.black_33,
    marginLeft: wp(1),
    fontSize: normalize(10),
    fontFamily: fonts.Lato_Regular,
    flex: 1,
  },
  editButton: {
    color: color.sky,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
    marginLeft: wp(1),
    marginTop: hp(3),
  },
  mapStyle: {
    // marginVertical: hp(2),
    // position: 'absolute',
    top: 0,
    left: 0,
    // right: -50,
    bottom: 0,

    flex: 1,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: wp(6),
  },
  progressBarText: {
    fontFamily: fonts.Lato_Bold,
    color: color.black_33,
    fontSize: normalize(12),
  },
  moreContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginHorizontal: wp(6),
  },
  moreText: {
    fontFamily: fonts.Lato_Regular,
    color: color.black_33,
    fontSize: normalize(12),
  },
  btnQrCode: {
    flexDirection: 'row',

    marginHorizontal: wp(6),

    borderRadius: wp(2),
    marginVertical: hp(1),
    flex: 1,
    alignItems: 'center',
    backgroundColor: color.sky,
  },
  tryProAccountContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    // marginHorizontal: wp(6),
    marginVertical: hp(1),
  },
  PurchaseMinutesContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginHorizontal: wp(6),
    marginVertical: hp(1),
  },
  tryProText1: {
    fontFamily: fonts.Lato_Regular,
    color: color.sky,
    fontSize: normalize(12),
  },
  btnQrText: {
    fontSize: normalize(12),
    color: color.white,
    textAlign: 'center',
    flex: 1,
    fontFamily: fonts.Lato_Bold,
  },
  tryProText2: {
    fontFamily: fonts.Lato_Regular,
    color: color.black_33,
    fontSize: normalize(12),
    left: wp(1),
  },
  basicContainer: {
    marginLeft: wp(6),
    marginRight: wp(1),
    borderColor: color.sky,
    borderWidth: 1,
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
  },
  basicSubTitle: {
    marginTop: hp(0.5),
    fontSize: normalize(10),
    fontFamily: fonts.Lato_Bold,
  },
  basicButton: {
    marginTop: hp(4),
    marginBottom: hp(3),
    width: wp(35),
    backgroundColor: color.transparent,
    alignSelf: 'center',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: color.sky,
  },
  basicButtonText: {
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Regular,
    color: color.sky,
  },
  proContainer: {
    marginRight: wp(6),
    marginLeft: wp(1),
    backgroundColor: color.black_33,
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: wp(2),
    paddingTop: hp(1),
    paddingBottom: hp(2),
  },
  proText: {
    marginTop: hp(0.5),
    color: color.white,
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Bold,
  },
  proTitle: {
    marginTop: hp(0.5),
    color: color.white,
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Bold,
  },
  proSubTitle: {
    marginTop: hp(0.5),
    color: color.white,
    fontSize: normalize(10),
    fontFamily: fonts.Lato_Bold,
  },
  proButton: {
    marginTop: hp(4),
    marginBottom: hp(3),
    flex: 1,
    width: wp(35),
    backgroundColor: color.sky,
    alignSelf: 'center',
    borderRadius: 5,
  },
  saveBtn: {
    borderRadius: 5,
    backgroundColor: color.sky,
    shadowOpacity: 0.2,
    marginHorizontal: wp(20),
  },
  dropdownContainer: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
  },
  textTitle: {
    fontFamily: fonts.Lato_Regular,
    fontSize: normalize(10),
    color: color.map_text_gray,
  },
  textValue: {
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(10),
    color: color.black_33,
  },

  textMapContainer: {
    position: 'absolute',
    zIndex: 100,
    top: isANDROID ? hp(18) : hp(20),
    marginHorizontal: wp(5),
  },
});

export default styles;
