import {StyleSheet} from 'react-native';
import {color, fonts, hp, normalize, wp} from '../../../../Helper/themeHelper';

const styles = StyleSheet.create({
  container: {
    paddingHorizontal: wp(5),
    // paddingVertical: hp(1),
    backgroundColor: color.lightest_gray,
  },
  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: hp(2),
    marginHorizontal: wp(3),
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  rowStyle: {
    paddingVertical: hp(2),
    paddingHorizontal: wp(2),
    marginLeft: wp(8),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  imageRowStyle: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    overflow: 'hidden',
    // borderWidth: 0.5,
  },
  logoInRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: wp(2),
  },
  sideTextStyle: {
    flex: 1,
    color: color.green_background,
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Regular,
  },
  headerTextStyle: {
    color: color.black,
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
  },
  inputContainer: {
    marginBottom: hp(2),
    marginTop: hp(2),
    backgroundColor: color.lightgray,
    borderRadius: wp(5),
    borderWidth: 0,
  },
  inputStyle: {
    fontSize: normalize(16),
    marginHorizontal: wp(1),
    borderWidth: 0,
  },
  sectionHeader: {
    paddingTop: 2,
    paddingLeft: wp(5),
    paddingRight: 10,
    paddingBottom: 2,
    fontSize: normalize(12),
    fontFamily: fonts.Lato_Bold,
    color: color.black,
    backgroundColor: color.light_background,
  },
  item: {
    padding: wp(2),
    fontSize: normalize(16),
    paddingLeft: wp(8),
  },
  viewOfImageStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp(20),
    marginRight: wp(2),
  },
  imageStyle: {
    height: wp(5),
    width: wp(5),
    marginTop: hp(10),
  },
  counterContainer: {
    flexDirection: 'row',
    backgroundColor: color.white,
    height: hp(10),
    justifyContent: 'space-between',
  },
  participantCounter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 0.5,
    borderRightColor: color.gray,
  },
  countersubText: {
    fontSize: normalize(10),
    fontFamily: fonts.Lato_Regular,
    color: color.gray,
  },
  counterMainText: {
    marginTop: hp(1),
    fontSize: normalize(14),
    fontFamily: fonts.Lato_Bold,
  },
  checkedCircle: {
    marginTop: 10,
    marginHorizontal: wp(2),
  },
  checkBoxView: {backgroundColor: color.green_background},
  itemSeparatorStyle: {
    height: hp(0.1),
    backgroundColor: color.gray,
    marginLeft: wp(10),
  },
  scrollBox: {
    flex: 1,
    height: hp(20),
    width: hp(18),
    marginLeft: wp(6),
    // marginRight: wp(2),
    marginTop: hp(1),
    marginBottom: hp(5),
    borderRadius: wp(3),
    backgroundColor: color.white,
    shadowColor: color.gray,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
  leftImage: {
    height: hp(8),
    width: hp(8),
    overflow: 'hidden',
    left: 20,
    alignSelf: 'center',
    borderRadius: hp(4),
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
  },

  btnLabelStyle: {
    fontFamily: fonts.Lato_Bold,
    fontSize: normalize(15),
    fontWeight: '700',
  },
  btnView: {flex: 1, marginLeft: wp(4)},
  centerImage: {
    height: hp(13),
    width: hp(13),
    borderRadius: hp(6.5),
    borderWidth: wp(1),
    borderColor: 'white',
    overflow: 'hidden',
    zIndex: 3,
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
  },

  rightImage: {
    height: hp(8),
    width: hp(8),
    overflow: 'hidden',
    right: 20,
    alignSelf: 'center',
    borderRadius: hp(4),
    shadowColor: 'rgba(0,0,0,0.97)',
    shadowOffset: {
      width: 5,
      height: 12,
    },
    shadowOpacity: 0.28,
    shadowRadius: 20.84,
  },

  headerText: {
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Regular,
    alignSelf: 'center',
    color: color.black_33,
    marginVertical: hp(2),
  },
  addOrFindButton: {
    width: wp(30),
    alignSelf: 'center',
    marginHorizontal: wp(1),
    borderRadius: hp(0.5),
    shadowRadius: 0,
    fontFamily: fonts.Lato_Bold,
    fontWeight: 'bold',
    fontSize: normalize(14),
    shadowColor: 0,
    elevation: 0,
  },
  findFriendBtnStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: hp(2),
    marginHorizontal: wp(3),
  },
  buttonStyle: {flex: 1, marginRight: wp(4)},
  textBold: {
    marginVertical: hp(1),
    marginHorizontal: wp(6),
    fontSize: normalize(16),
    fontFamily: fonts.Lato_Bold,
    color: color.black_33,
  },
  suggestedFriendImage: {
    marginVertical: hp(1),
    height: hp(8),
    width: hp(8),
    borderRadius: hp(5),
    overflow: 'hidden',
    alignSelf: 'center',
  },
  addButton: {
    width: wp(20),
    height: hp(4),
    alignSelf: 'center',

    paddingVertical: hp(0),
    marginHorizontal: wp(2),
    marginVertical: hp(2),
    backgroundColor: color.sky,
    borderRadius: hp(0.5),
    shadowRadius: 0,
    shadowColor: 0,
    elevation: 0,
  },
  indexContainer: {
    flex: 1,
    marginVertical: hp(2),
    marginHorizontal: wp(6),
    borderRadius: hp(2),
    shadowColor: color.gray,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
    backgroundColor: color.white,
  },
  selectedContactMainView: {
    paddingVertical: hp(1),
    paddingHorizontal: wp(4),
    backgroundColor: color.white,
  },
  selectedContactInnerView: {
    alignItems: 'center',
    paddingHorizontal: wp(1.5),
  },
  selectedContactImage: {
    width: wp(11),
    height: wp(11),
    borderRadius: wp(5.5),
    // borderWidth: 0.5,
  },
  selectedParticipantImage: {
    width: wp(13),
    height: wp(13),
    borderRadius: wp(6.5),
    // borderWidth: 0.5,
  },
  selectedContactButtonView: {
    height: hp(2),
    width: hp(2),
    backgroundColor: color.sky,
    borderRadius: hp(2),
    position: 'absolute',
    top: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedCloseButtonView: {
    height: hp(2),
    width: hp(2),
    backgroundColor: color.gray,
    borderRadius: hp(2),
    position: 'absolute',
    top: wp(4),
    right: wp(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
