module.exports = {
  // BASE_URL: 'https://olie.herokuapp.com',
  BASE_URL: 'http://15.207.118.193:500',
  // BASE_URL: 'http://192.168.0.2:500',
  FETCH_USER_DETAILS: '/api/user',
  SIGN_UP: '/api/auth/register',
  REGISTER_EXTERNAL_LOGIN: '/api/auth/register_using_external_login',
  LOGIN: '/api/auth/login',
  GET_SETTING: '/api/setting',
  UPDATE_SETTING: '/api/setting/update',
  EXTERNAL_LOGIN: '/api/auth/external_login',
  EDIT_PROFILE: '/api/user/edit_profile',
  FETCH_FRIENDS: '/api/friends/fetch',
  FETCH_REPAIR_SHOP: '/api/repair_shop/',
  FIND_FRIENDS: '/api/friends/find_friends',
  FETCH_RENTALS: '/api/rental/',
  FETCH_FAVORITE_ROUTES_BY_USER: '/api/route/favorite',
  ADD_FRIENDS: '/api/friends/add',
  FETCH_GROUPS: '/api/group',
  FETCH_GROUP_RIDEOUTS: '/api/group_ride_out',
  SET_FAVOURITE_ROUTE: '/api/route/is_favorite',
  FETCH_ROUTES: '/api/route',
  FETCH_GROUP_ROUTES: '/api/route/group',
  CREATE_ROUTES: '/api/route/create',
  CREATE_GROUP: '/api/group/create',
  ADD_BY_PHONE: '/api/friends/add_by_phone',
  ADD_BY_EMAIL: '/api/friends/add_by_email',
  UPLOAD_FILE_CHAT: '/api/message/upload_file',
  UPDATE_PARTICIPANTS: '/api/group/update_participants',
  UPDATE_ADD_ADMIN: '/api/group/update_group_admin',
  UPDATE_GROUP: '/api/group/update/',
  FETCH_GROUP_MEDIA: '/api/group/media/',
  CLEAR_CHAT: '/api/group/clear_chat',
  EXIT_GROUP: '/api/group/exit_group',
  FETCH_CHALLENGES: '/api/challenge/',
  FETCH_POPULAR_CHALLENGES: '/api/challenge/fetch_popular',
  FETCH_NEW_CHALLENGES: '/api/challenge/fetch_new',
  SUBSCRIPT_CHALLENGE_BY_ID: '/api/challenge/subscribe',
  FETCH_USER_ACTIVITIES: '/api/activity/this_week',
  FETCH_USER_RECENT_RIDE: '/api/activity/recent_ride',
  FETCH_USER_BEST_RIDE: '/api/activity/best_ride',
  CREATE_ACTIVITY: '/api/activity/create',
  SIGN_OUT: '/api/auth/logout_user',
  MUTE_GROUP: '/api/group/mute_user_group',
  FETCH_NEAREST_SHOPS: '/api/repair_shop/fetch_nearest',
  FETCH_USER_ACHIEVEMENTS: '/api/user_achievement/fetch_by_user',
};
